name: pgsc_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pgscatalog_utils==1.4.4
      - pgscatalog.core==0.3.3
      - pgscatalog.match==0.3.3
      - pgscatalog.calc==0.3.0
  - zstd=1.4.8
  - tar=1.34
  - bioconda::plink2==2.00a5.10
  - conda-forge::pyyaml==6.0.1
